// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AccessibilityTestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UIAccessibilityExampleWindow UIAccessibilityExampleWindow
        {
            get
            {
                if ((this.mUIAccessibilityExampleWindow == null))
                {
                    this.mUIAccessibilityExampleWindow = new UIAccessibilityExampleWindow();
                }
                return this.mUIAccessibilityExampleWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAccessibilityExampleWindow mUIAccessibilityExampleWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIAccessibilityExampleWindow : XamlWindow
    {
        
        public UIAccessibilityExampleWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Accessibility Example";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("Accessibility Example");
            #endregion
        }
        
        #region Properties
        public XamlEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "NameTextBox";
                    this.mUINameEdit.WindowTitles.Add("Accessibility Example");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        
        public XamlEdit UIAgeEdit
        {
            get
            {
                if ((this.mUIAgeEdit == null))
                {
                    this.mUIAgeEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUIAgeEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "AgeTextBox";
                    this.mUIAgeEdit.WindowTitles.Add("Accessibility Example");
                    #endregion
                }
                return this.mUIAgeEdit;
            }
        }
        
        public XamlText UINameisRequiredText
        {
            get
            {
                if ((this.mUINameisRequiredText == null))
                {
                    this.mUINameisRequiredText = new XamlText(this);
                    #region Search Criteria
                    this.mUINameisRequiredText.SearchProperties[XamlText.PropertyNames.AutomationId] = "NameError";
                    this.mUINameisRequiredText.WindowTitles.Add("Accessibility Example");
                    #endregion
                }
                return this.mUINameisRequiredText;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUINameEdit;
        
        private XamlEdit mUIAgeEdit;
        
        private XamlText mUINameisRequiredText;
        #endregion
    }
}
